export const characters = [
  // Stars Category
  { name: 'Black star', character: '★', categories: ['Stars', 'Shapes'] },
  { name: 'White star', character: '☆', categories: ['Stars', 'Shapes'] },
  { name: 'Star with shadow', character: '✪', categories: ['Stars', 'Shapes'] },
  { name: 'Star', character: '✰', categories: ['Stars', 'Shapes'] },

  // Currency Category
  { name: 'Dollar sign', character: '$', categories: ['Currency'] },
  { name: 'Cent sign', character: '¢', categories: ['Currency'] },
  { name: 'Pound sign', character: '£', categories: ['Currency'] },
  { name: 'Yen sign', character: '¥', categories: ['Currency'] },
  { name: 'Currency sign', character: '¤', categories: ['Currency'] },
  { name: 'New Sheqel sign', character: '₪', categories: ['Currency'] },
  { name: 'Euro sign', character: '€', categories: ['Currency'] },
  { name: 'Lira sign', character: '₤', categories: ['Currency'] },
  { name: 'Naira sign', character: '₦', categories: ['Currency'] },
  { name: 'Peseta sign', character: '₧', categories: ['Currency'] },
  { name: 'Rupee sign', character: '₨', categories: ['Currency'] },
  { name: 'Won sign', character: '₩', categories: ['Currency'] },
  { name: 'Tugrik sign', character: '₮', categories: ['Currency'] },
  { name: 'Peso sign', character: '₱', categories: ['Currency'] },
  { name: 'Guarani sign', character: '₲', categories: ['Currency'] },
  { name: 'Austral sign', character: '₳', categories: ['Currency'] },
  { name: 'Hryvnia sign', character: '₴', categories: ['Currency'] },
  { name: 'Cedi sign', character: '₵', categories: ['Currency'] },
  { name: 'Kip sign', character: '₭', categories: ['Currency'] },
  { name: 'Turkish Lira sign', character: '₺', categories: ['Currency'] },
  { name: 'Manat sign', character: '₼', categories: ['Currency'] },
  { name: 'Ruble sign', character: '₽', categories: ['Currency'] },
  { name: 'Lari sign', character: '₾', categories: ['Currency'] },

  // Basic symbols Category
  { name: 'Hash symbol', character: '#', categories: ['Basic symbols'] },
  { name: 'At symbol', character: '@', categories: ['Basic symbols'] },
  {
    name: 'Exclamation mark symbol',
    character: '!',
    categories: ['Basic symbols'],
  },
  { name: 'Percent symbol', character: '%', categories: ['Basic symbols'] },
  { name: 'Ampersand symbol', character: '&', categories: ['Basic symbols'] },
  { name: 'Asterisk symbol', character: '*', categories: ['Basic symbols'] },
  { name: 'Plus symbol', character: '+', categories: ['Basic symbols'] },
  { name: 'Minus symbol', character: '-', categories: ['Basic symbols'] },
  { name: 'Equals symbol', character: '=', categories: ['Basic symbols'] },
  { name: 'Caret symbol', character: '^', categories: ['Basic symbols'] },
  { name: 'Underscore symbol', character: '_', categories: ['Basic symbols'] },
  { name: 'Tilde symbol', character: '~', categories: ['Basic symbols'] },
  { name: 'Period symbol', character: '.', categories: ['Basic symbols'] },
  { name: 'Comma symbol', character: ',', categories: ['Basic symbols'] },
  { name: 'Colon symbol', character: ':', categories: ['Basic symbols'] },
  { name: 'Semicolon symbol', character: ';', categories: ['Basic symbols'] },
  {
    name: 'Double quote symbol',
    character: '"',
    categories: ['Basic symbols'],
  },
  {
    name: 'Single quote symbol',
    character: "'",
    categories: ['Basic symbols'],
  },
  { name: 'Backtick symbol', character: '`', categories: ['Basic symbols'] },

  // Punctuation
  { name: 'Question mark symbol', character: '?', categories: ['Punctuation'] },
  { name: 'Open parenthesis', character: '(', categories: ['Punctuation'] },
  { name: 'Close parenthesis', character: ')', categories: ['Punctuation'] },
  { name: 'Open bracket', character: '[', categories: ['Punctuation'] },
  { name: 'Close bracket', character: ']', categories: ['Punctuation'] },
  { name: 'Open brace', character: '{', categories: ['Punctuation'] },
  { name: 'Close brace', character: '}', categories: ['Punctuation'] },
  { name: 'Less than', character: '<', categories: ['Punctuation'] },
  { name: 'Greater than', character: '>', categories: ['Punctuation'] },
  { name: 'Slash', character: '/', categories: ['Punctuation'] },
  { name: 'Vertical bar', character: '|', categories: ['Punctuation'] },

  // Shapes
  { name: 'Black four-pointed star', character: '✦', categories: ['Shapes'] },
  { name: 'White four-pointed star', character: '✧', categories: ['Shapes'] },
  {
    name: 'Heavy white four-pointed star',
    character: '⭑',
    categories: ['Shapes'],
  },
  { name: 'Black diamond', character: '◆', categories: ['Shapes'] },
  { name: 'White diamond', character: '◇', categories: ['Shapes'] },
  { name: 'Fisheye', character: '◉', categories: ['Shapes'] },
  { name: 'White circle', character: '○', categories: ['Shapes'] },
  { name: 'Bullseye', character: '◎', categories: ['Shapes'] },
  { name: 'Black circle', character: '●', categories: ['Shapes'] },
  { name: 'Black square', character: '■', categories: ['Shapes'] },
  { name: 'White square', character: '□', categories: ['Shapes'] },
  {
    name: 'Black up-pointing triangle',
    character: '▲',
    categories: ['Shapes'],
  },
  {
    name: 'White up-pointing triangle',
    character: '△',
    categories: ['Shapes'],
  },
  {
    name: 'Black down-pointing triangle',
    character: '▼',
    categories: ['Shapes'],
  },
  {
    name: 'White down-pointing triangle',
    character: '▽',
    categories: ['Shapes'],
  },

  // Cards
  { name: 'Spade suit', character: '♠', categories: ['Cards'] },
  { name: 'Club suit', character: '♣', categories: ['Cards'] },
  { name: 'Heart suit', character: '♥', categories: ['Cards'] },
  { name: 'Diamond suit', character: '♦', categories: ['Cards'] },
  { name: 'White spade suit', character: '♤', categories: ['Cards'] },
  { name: 'White club suit', character: '♧', categories: ['Cards'] },
  { name: 'White heart suit', character: '♡', categories: ['Cards'] },
  { name: 'White diamond suit', character: '♢', categories: ['Cards'] },

  // Chess
  { name: 'White king', character: '♔', categories: ['Chess'] },
  { name: 'White queen', character: '♕', categories: ['Chess'] },
  { name: 'White rook', character: '♖', categories: ['Chess'] },
  { name: 'White bishop', character: '♗', categories: ['Chess'] },
  { name: 'White knight', character: '♘', categories: ['Chess'] },
  { name: 'White pawn', character: '♙', categories: ['Chess'] },
  { name: 'Black king', character: '♚', categories: ['Chess'] },
  { name: 'Black queen', character: '♛', categories: ['Chess'] },
  { name: 'Black rook', character: '♜', categories: ['Chess'] },
  { name: 'Black bishop', character: '♝', categories: ['Chess'] },
  { name: 'Black knight', character: '♞', categories: ['Chess'] },
  { name: 'Black pawn', character: '♟', categories: ['Chess'] },

  // Music
  { name: 'Quarter note', character: '♩', categories: ['Music'] },
  { name: 'Eighth note', character: '♪', categories: ['Music'] },
  { name: 'Beamed eighth notes', character: '♫', categories: ['Music'] },
  { name: 'Beamed sixteenth notes', character: '♬', categories: ['Music'] },
  { name: 'Music flat sign', character: '♭', categories: ['Music'] },
  { name: 'Music natural sign', character: '♮', categories: ['Music'] },
  { name: 'Music sharp sign', character: '♯', categories: ['Music'] },

  // Other symbols
  { name: 'Recycle', character: '♺', categories: ['Other symbols'] },
  {
    name: 'Universal recycling symbol',
    character: '♻',
    categories: ['Other symbols'],
  },
  {
    name: 'Recycled paper symbol',
    character: '♼',
    categories: ['Other symbols'],
  },
  {
    name: 'Partially recycled paper symbol',
    character: '♽',
    categories: ['Other symbols'],
  },
  {
    name: 'Permanent paper sign',
    character: '♾',
    categories: ['Other symbols'],
  },
  { name: 'Die face-1', character: '⚀', categories: ['Other symbols'] },
  { name: 'Die face-2', character: '⚁', categories: ['Other symbols'] },
  { name: 'Die face-3', character: '⚂', categories: ['Other symbols'] },
  { name: 'Die face-4', character: '⚃', categories: ['Other symbols'] },
  { name: 'Die face-5', character: '⚄', categories: ['Other symbols'] },
  { name: 'Die face-6', character: '⚅', categories: ['Other symbols'] },
  {
    name: 'White circle with dot right',
    character: '⚆',
    categories: ['Other symbols'],
  },
  {
    name: 'Inverse white circle with dot right',
    character: '⚇',
    categories: ['Other symbols'],
  },
  {
    name: 'White circle with two dots',
    character: '⚈',
    categories: ['Other symbols'],
  },
  {
    name: 'Inverse white circle with two dots',
    character: '⚉',
    categories: ['Other symbols'],
  },
  { name: 'Black flag', character: '⚐', categories: ['Other symbols'] },
  { name: 'White flag', character: '⚑', categories: ['Other symbols'] },
  { name: 'Hammer and pick', character: '⚒', categories: ['Other symbols'] },
  { name: 'Anchor', character: '⚓', categories: ['Other symbols'] },
  { name: 'Crossed swords', character: '⚔', categories: ['Other symbols'] },
  { name: 'Medical symbol', character: '⚕', categories: ['Other symbols'] },
  { name: 'Scales', character: '⚖', categories: ['Other symbols'] },
  { name: 'Alembic', character: '⚗', categories: ['Other symbols'] },
  { name: 'Flower', character: '⚘', categories: ['Other symbols'] },
  { name: 'Gear', character: '⚙', categories: ['Other symbols'] },
  { name: 'Staff of Hermes', character: '⚚', categories: ['Other symbols'] },
  { name: 'Atom symbol', character: '⚛', categories: ['Other symbols'] },
  { name: 'Fleur-de-lis', character: '⚜', categories: ['Other symbols'] },
  { name: 'Outlined star', character: '⚝', categories: ['Other symbols'] },
  {
    name: 'Three lines converging right',
    character: '⚞',
    categories: ['Other symbols'],
  },
  {
    name: 'Three lines converging left',
    character: '⚟',
    categories: ['Other symbols'],
  },
  { name: 'Warning', character: '⚠', categories: ['Other symbols'] },
  {
    name: 'Doubled female sign',
    character: '⚢',
    categories: ['Other symbols'],
  },
  { name: 'Doubled male sign', character: '⚣', categories: ['Other symbols'] },
  {
    name: 'Interlocked male and female sign',
    character: '⚤',
    categories: ['Other symbols'],
  },
  {
    name: 'Male and female sign',
    character: '⚥',
    categories: ['Other symbols'],
  },
  {
    name: 'Male with stroke sign',
    character: '⚦',
    categories: ['Other symbols'],
  },
  {
    name: 'Male with stroke and male and female sign',
    character: '⚧',
    categories: ['Other symbols'],
  },
  {
    name: 'Vertical line with circle above',
    character: '⚨',
    categories: ['Other symbols'],
  },
  {
    name: 'Horizontal male with stroke sign',
    character: '⚩',
    categories: ['Other symbols'],
  },
  {
    name: 'Medium small white circle',
    character: '⚬',
    categories: ['Other symbols'],
  },
  { name: 'Marriage symbol', character: '⚭', categories: ['Other symbols'] },
  { name: 'Divorce symbol', character: '⚮', categories: ['Other symbols'] },
  {
    name: 'Unmarried partnership symbol',
    character: '⚯',
    categories: ['Other symbols'],
  },
  { name: 'Coffin', character: '⚰', categories: ['Other symbols'] },
  { name: 'Funeral urn', character: '⚱', categories: ['Other symbols'] },
  { name: 'Neuter', character: '⚲', categories: ['Other symbols'] },
  { name: 'Earth', character: '⚳', categories: ['Other symbols'] },
  { name: 'Earth retrograde', character: '⚴', categories: ['Other symbols'] },
  { name: 'Ascelpius staff', character: '⚵', categories: ['Other symbols'] },
  { name: 'Mercury', character: '⚶', categories: ['Other symbols'] },
  { name: 'Mercury retrograde', character: '⚷', categories: ['Other symbols'] },
  { name: 'Venus', character: '⚸', categories: ['Other symbols'] },
  { name: 'Venus retrograde', character: '⚹', categories: ['Other symbols'] },
  { name: 'Mars', character: '⚺', categories: ['Other symbols'] },
  { name: 'Mars retrograde', character: '⚻', categories: ['Other symbols'] },
  { name: 'Jupiter', character: '⚼', categories: ['Other symbols'] },
  { name: 'Jupiter retrograde', character: '⚿', categories: ['Other symbols'] },
  { name: 'Saturn', character: '⛀', categories: ['Other symbols'] },
  { name: 'Saturn retrograde', character: '⛁', categories: ['Other symbols'] },
  { name: 'Uranus', character: '⛂', categories: ['Other symbols'] },
  { name: 'Uranus retrograde', character: '⛃', categories: ['Other symbols'] },
  { name: 'Neptune', character: '⛆', categories: ['Other symbols'] },
  { name: 'Neptune retrograde', character: '⛇', categories: ['Other symbols'] },
  { name: 'Pluto', character: '⛈', categories: ['Other symbols'] },
  { name: 'Pluto retrograde', character: '⛉', categories: ['Other symbols'] },
  { name: 'Aries', character: '⛊', categories: ['Other symbols'] },
  { name: 'Taurus', character: '⛋', categories: ['Other symbols'] },
  { name: 'Gemini', character: '⛌', categories: ['Other symbols'] },
  { name: 'Cancer', character: '⛍', categories: ['Other symbols'] },
  { name: 'Leo', character: '⛏', categories: ['Other symbols'] },
  { name: 'Virgo', character: '⛐', categories: ['Other symbols'] },
  { name: 'Libra', character: '⛑', categories: ['Other symbols'] },
  { name: 'Scorpio', character: '⛒', categories: ['Other symbols'] },
  { name: 'Sagittarius', character: '⛓', categories: ['Other symbols'] },
  { name: 'Capricorn', character: '⛕', categories: ['Other symbols'] },
  { name: 'Aquarius', character: '⛖', categories: ['Other symbols'] },
  { name: 'Pisces', character: '⛗', categories: ['Other symbols'] },
  { name: 'Alpha', character: '⛘', categories: ['Other symbols'] },
  { name: 'Beta', character: '⛙', categories: ['Other symbols'] },
  { name: 'Gamma', character: '⛚', categories: ['Other symbols'] },
  { name: 'Delta', character: '⛛', categories: ['Other symbols'] },
  { name: 'Epsilon', character: '⛜', categories: ['Other symbols'] },
  { name: 'Zeta', character: '⛝', categories: ['Other symbols'] },
  { name: 'Eta', character: '⛞', categories: ['Other symbols'] },
  { name: 'Theta', character: '⛟', categories: ['Other symbols'] },
  { name: 'Iota', character: '⛠', categories: ['Other symbols'] },
  { name: 'Kappa', character: '⛡', categories: ['Other symbols'] },
  { name: 'Lambda', character: '⛢', categories: ['Other symbols'] },
  { name: 'Mu', character: '⛣', categories: ['Other symbols'] },
  { name: 'Nu', character: '⛤', categories: ['Other symbols'] },
  { name: 'Xi', character: '⛥', categories: ['Other symbols'] },
  { name: 'Omicron', character: '⛦', categories: ['Other symbols'] },
  { name: 'Pi', character: '⛧', categories: ['Other symbols'] },
  { name: 'Rho', character: '⛨', categories: ['Other symbols'] },
  { name: 'Sigma', character: '⛩', categories: ['Other symbols'] },
  { name: 'Tau', character: '⛫', categories: ['Other symbols'] },
  { name: 'Upsilon', character: '⛬', categories: ['Other symbols'] },
  { name: 'Phi', character: '⛭', categories: ['Other symbols'] },
  { name: 'Chi', character: '⛮', categories: ['Other symbols'] },
  { name: 'Psi', character: '⛯', categories: ['Other symbols'] },
  { name: 'Omega', character: '⛰', categories: ['Other symbols'] },
  { name: 'Open umbrella', character: '⛱', categories: ['Other symbols'] },
  { name: 'Ferry', character: '⛴', categories: ['Other symbols'] },
  {
    name: 'Square four corners',
    character: '⛶',
    categories: ['Other symbols'],
  },
  { name: 'Skier', character: '⛷', categories: ['Other symbols'] },
  { name: 'Ice skate', character: '⛸', categories: ['Other symbols'] },
  { name: 'Carousel horse', character: '⛻', categories: ['Other symbols'] },
  {
    name: 'Triangle flag on post',
    character: '⛼',
    categories: ['Other symbols'],
  },
  { name: 'Japanese lantern', character: '⛾', categories: ['Other symbols'] },
  {
    name: 'Triangle with rounded corners',
    character: '⛿',
    categories: ['Other symbols'],
  },

  // Others
  { name: 'Copyright', character: '©', categories: ['Others'] },
  { name: 'Registered', character: '®', categories: ['Others'] },
  { name: 'Trademark', character: '™', categories: ['Others'] },
  { name: 'Section', character: '§', categories: ['Others'] },
  { name: 'Pilcrow', character: '¶', categories: ['Others'] },
  { name: 'Bullet', character: '•', categories: ['Others'] },
  { name: 'Dagger', character: '†', categories: ['Others'] },
  { name: 'Double dagger', character: '‡', categories: ['Others'] },
  { name: 'Degree', character: '°', categories: ['Others'] },
  { name: 'Plus-minus', character: '±', categories: ['Others'] },
  { name: 'Micro', character: 'µ', categories: ['Others'] },
  { name: 'Double vertical line', character: '‖', categories: ['Others'] },
  { name: 'Half', character: '½', categories: ['Others'] },
  { name: 'Quarter', character: '¼', categories: ['Others'] },
  { name: 'Three quarters', character: '¾', categories: ['Others'] },
  { name: 'Superscript two', character: '²', categories: ['Others'] },
  { name: 'Superscript three', character: '³', categories: ['Others'] },
  { name: 'Subscript one', character: '₁', categories: ['Others'] },
  { name: 'Subscript two', character: '₂', categories: ['Others'] },
  { name: 'Subscript three', character: '₃', categories: ['Others'] },
  { name: 'Account of', character: '℀', categories: ['Others'] },
  { name: 'Addressed to the subject', character: '℁', categories: ['Others'] },
  { name: 'Double-struck capital C', character: 'ℂ', categories: ['Others'] },
  { name: 'Care of', character: '℅', categories: ['Others'] },
  { name: 'Cada una', character: '℆', categories: ['Others'] },
  { name: 'Euler constant', character: 'ℇ', categories: ['Others'] },
  { name: 'Fahrenheit', character: '℉', categories: ['Others'] },
  { name: 'Script small g', character: 'ℊ', categories: ['Others'] },
  { name: 'Script capital H', character: 'ℋ', categories: ['Others'] },
  { name: 'Black-letter capital H', character: 'ℌ', categories: ['Others'] },
  { name: 'Double-struck capital H', character: 'ℍ', categories: ['Others'] },
  { name: 'Planck constant', character: 'ℎ', categories: ['Others'] },
  { name: 'Reduced Planck constant', character: 'ℏ', categories: ['Others'] },
  { name: 'Script capital I', character: 'ℐ', categories: ['Others'] },
  { name: 'Black-letter capital I', character: 'ℑ', categories: ['Others'] },
  { name: 'Script capital L', character: 'ℒ', categories: ['Others'] },
  { name: 'Script small L', character: 'ℓ', categories: ['Others'] },
  { name: 'L b Bar', character: '℔', categories: ['Others'] },
  { name: 'Double-struck capital N', character: 'ℕ', categories: ['Others'] },
  { name: 'Numero sign', character: '№', categories: ['Others'] },
  { name: 'Sound recording copyright', character: '℗', categories: ['Others'] },
  { name: 'Double-struck capital P', character: 'ℙ', categories: ['Others'] },
  { name: 'Double-struck capital Q', character: 'ℚ', categories: ['Others'] },
  { name: 'Double-struck capital R', character: 'ℛ', categories: ['Others'] },
  { name: 'Black-letter capital R', character: 'ℜ', categories: ['Others'] },
  { name: 'Double-struck capital R', character: 'ℝ', categories: ['Others'] },
  { name: 'Prescription', character: '℞', categories: ['Others'] },
  { name: 'Response', character: '℟', categories: ['Others'] },
  { name: 'Service mark', character: '℠', categories: ['Others'] },
  { name: 'Telephone sign', character: '℡', categories: ['Others'] },
  { name: 'Versicle', character: '℣', categories: ['Others'] },
  { name: 'Double-struck capital Z', character: 'ℤ', categories: ['Others'] },
  { name: 'Ounce', character: '℥', categories: ['Others'] },
  { name: 'Ohm sign', character: 'Ω', categories: ['Others'] },
  { name: 'Inverted ohm sign', character: '℧', categories: ['Others'] },
  { name: 'Script capital Z', character: 'ℨ', categories: ['Others'] },
  {
    name: 'Turned Greek small letter iota',
    character: '℩',
    categories: ['Others'],
  },
  { name: 'Kelvin', character: 'K', categories: ['Others'] },
  { name: 'Angstrom sign', character: 'Å', categories: ['Others'] },
  { name: 'Script capital B', character: 'ℬ', categories: ['Others'] },
  { name: 'Black-letter capital C', character: 'ℭ', categories: ['Others'] },
  { name: 'Estimated', character: '℮', categories: ['Others'] },
  { name: 'Script small e', character: 'ℯ', categories: ['Others'] },
  { name: 'Script capital E', character: 'ℰ', categories: ['Others'] },
  { name: 'Script capital F', character: 'ℱ', categories: ['Others'] },
  { name: 'Turned capital F', character: 'Ⅎ', categories: ['Others'] },
  { name: 'Script capital M', character: 'ℳ', categories: ['Others'] },
  { name: 'Script small o', character: 'ℴ', categories: ['Others'] },
  { name: 'Alef symbol', character: 'ℵ', categories: ['Others'] },
  { name: 'Bet symbol', character: 'ℶ', categories: ['Others'] },
  { name: 'Gimel symbol', character: 'ℷ', categories: ['Others'] },
  { name: 'Dalet symbol', character: 'ℸ', categories: ['Others'] },
  { name: 'Information source', character: 'ℹ', categories: ['Others'] },
  { name: 'Turned capital Q', character: '℺', categories: ['Others'] },
  { name: 'Facsimile sign', character: '℻', categories: ['Others'] },
  { name: 'Pi', character: 'ℼ', categories: ['Others'] },
  { name: 'Gamma', character: 'ℽ', categories: ['Others'] },
  { name: 'Gamma', character: 'ℾ', categories: ['Others'] },
  { name: 'Capital pi', character: 'ℿ', categories: ['Others'] },
  { name: 'Double-struck capital S', character: '⅀', categories: ['Others'] },
  {
    name: 'Turned sans-serif capital G',
    character: '⅁',
    categories: ['Others'],
  },
  { name: 'Sans-serif capital L', character: '⅂', categories: ['Others'] },
  {
    name: 'Reversed sans-serif capital L',
    character: '⅃',
    categories: ['Others'],
  },
  {
    name: 'Turned sans-serif capital Y',
    character: '⅄',
    categories: ['Others'],
  },
  { name: 'Double-struck capital D', character: 'ⅅ', categories: ['Others'] },
  { name: 'Double-struck small d', character: 'ⅆ', categories: ['Others'] },
  { name: 'Double-struck small e', character: 'ⅇ', categories: ['Others'] },
  { name: 'Double-struck small i', character: 'ⅈ', categories: ['Others'] },
  { name: 'Double-struck small j', character: 'ⅉ', categories: ['Others'] },
  { name: 'Property line', character: '⅊', categories: ['Others'] },
  { name: 'Turned ampersand', character: '⅋', categories: ['Others'] },
  { name: 'Property line', character: '⅌', categories: ['Others'] },
  { name: 'Script capital I', character: '⅍', categories: ['Others'] },
  { name: 'Inverted capital N', character: 'ⅎ', categories: ['Others'] },
  { name: 'Roman numeral one', character: 'Ⅰ', categories: ['Others'] },
  { name: 'Roman numeral two', character: 'Ⅱ', categories: ['Others'] },
  { name: 'Roman numeral three', character: 'Ⅲ', categories: ['Others'] },
  { name: 'Roman numeral four', character: 'Ⅳ', categories: ['Others'] },
  { name: 'Roman numeral five', character: 'Ⅴ', categories: ['Others'] },
  { name: 'Roman numeral six', character: 'Ⅵ', categories: ['Others'] },
  { name: 'Roman numeral seven', character: 'Ⅶ', categories: ['Others'] },
  { name: 'Roman numeral eight', character: 'Ⅷ', categories: ['Others'] },
  { name: 'Roman numeral nine', character: 'Ⅸ', categories: ['Others'] },
  { name: 'Roman numeral ten', character: 'Ⅹ', categories: ['Others'] },
  { name: 'Roman numeral eleven', character: 'Ⅺ', categories: ['Others'] },
  { name: 'Roman numeral twelve', character: 'Ⅻ', categories: ['Others'] },
  { name: 'Roman numeral fifty', character: 'Ⅼ', categories: ['Others'] },
  { name: 'Roman numeral one hundred', character: 'Ⅽ', categories: ['Others'] },
  {
    name: 'Roman numeral five hundred',
    character: 'Ⅾ',
    categories: ['Others'],
  },
  {
    name: 'Roman numeral one thousand',
    character: 'Ⅿ',
    categories: ['Others'],
  },
];
